# FROM python:2.7-alpine
FROM jfloff/alpine-python:2.7

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
            gcc \
            make \
            libc-dev \
            musl-dev \
            linux-headers \
            pcre-dev \
            python-dev \
    && apk add --no-cache mariadb-dev \
    && sed '/st_mysql_options options;/a unsigned int reconnect;' /usr/include/mysql/mysql.h -i.bkp \
    && pip install --no-cache-dir MySQL-python==1.2.3rc1 \
    && runDeps="$( \
            scanelf --needed --nobanner --recursive /venv \
                    | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
                    | sort -u \
                    | xargs -r apk info --installed \
                    | sort -u \
    )" \
    && apk add --virtual .python-rundeps $runDeps \
    && apk del .build-deps

COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY ./notejam /notejam

WORKDIR /notejam

# RUN python manage.py syncdb
# RUN python manage.py migrate

EXPOSE 8000

CMD exec gunicorn notejam.wsgi:application --bind 0.0.0.0:8000 --workers 3